pipeline {
  agent {
    docker {
      image 'printcap/cuda_jvmci_mx:10.0_ubuntu16.04'
    }
  }
  stages {
    stage('Build') {
      steps {
        sh 'ci/build.sh'
      }
    }
    stage('Test') {
      steps {
        sh 'ci/test.sh'
      }
    }
  }
}
